package catalogue

// Ecosystem identifies the language-level package manager used as a fallback.
type Ecosystem string

const (
	EcosystemNone  Ecosystem = ""
	EcosystemPip   Ecosystem = "pip"
	EcosystemGo    Ecosystem = "go"
	EcosystemCargo Ecosystem = "cargo"
	EcosystemGem   Ecosystem = "gem"
	EcosystemNpm   Ecosystem = "npm"
)

// Tool holds all metadata for a single security tool.
type Tool struct {
	Name         string
	DisplayName  string
	Category     string
	PkgArch      string    // primary pacman/AUR package
	PkgDeb       string    // primary apt package
	PkgAliasArch []string  // fallback package names for Arch
	PkgAliasDeb  []string  // fallback package names for Debian
	Ecosystem    Ecosystem // pip / go / cargo / gem / npm
	EcosystemPkg string    // package/module identifier for that ecosystem
	Cmd          string    // binary to run
	KaliSlug     string    // kali.org/tools/<slug>
	Description  string    // populated at runtime
	Homepage     string    // populated at runtime
	IconPath     string    // populated at runtime
	IsCustom     bool
}

// AllTools returns the full ordered tool catalogue.
func AllTools() []Tool {
	return []Tool{

		// ── Information Gathering ────────────────────────────────────────────────
		{Name: "nmap", DisplayName: "Nmap", Category: "Information Gathering",
			PkgArch: "nmap", PkgDeb: "nmap", Cmd: "nmap", KaliSlug: "nmap"},
		{Name: "masscan", DisplayName: "Masscan", Category: "Information Gathering",
			PkgArch: "masscan", PkgDeb: "masscan", Cmd: "masscan", KaliSlug: "masscan"},
		{Name: "rustscan", DisplayName: "RustScan", Category: "Information Gathering",
			PkgArch: "rustscan", PkgDeb: "rustscan",
			PkgAliasArch: []string{"rustscan-bin"},
			Ecosystem: EcosystemCargo, EcosystemPkg: "rustscan",
			Cmd: "rustscan", KaliSlug: "rustscan"},
		{Name: "zmap", DisplayName: "ZMap", Category: "Information Gathering",
			PkgArch: "zmap", PkgDeb: "zmap", Cmd: "zmap", KaliSlug: "zmap"},
		{Name: "unicornscan", DisplayName: "Unicornscan", Category: "Information Gathering",
			PkgArch: "unicornscan", PkgDeb: "unicornscan", Cmd: "unicornscan", KaliSlug: "unicornscan"},
		{Name: "whatweb", DisplayName: "WhatWeb", Category: "Information Gathering",
			PkgArch: "whatweb", PkgDeb: "whatweb",
			PkgAliasDeb: []string{"ruby-whatweb"},
			Cmd: "whatweb", KaliSlug: "whatweb"},
		{Name: "theharvester", DisplayName: "theHarvester", Category: "Information Gathering",
			PkgArch: "theharvester", PkgDeb: "theharvester",
			PkgAliasDeb: []string{"python3-theharvester"},
			Ecosystem: EcosystemPip, EcosystemPkg: "theHarvester",
			Cmd: "theHarvester", KaliSlug: "theharvester"},
		{Name: "recon-ng", DisplayName: "Recon-ng", Category: "Information Gathering",
			PkgArch: "recon-ng", PkgDeb: "recon-ng",
			Ecosystem: EcosystemPip, EcosystemPkg: "recon-ng",
			Cmd: "recon-ng", KaliSlug: "recon-ng"},
		{Name: "maltego", DisplayName: "Maltego", Category: "Information Gathering",
			PkgArch: "maltego", PkgDeb: "maltego", Cmd: "maltego", KaliSlug: "maltego"},
		{Name: "shodan", DisplayName: "Shodan CLI", Category: "Information Gathering",
			PkgArch: "python-shodan", PkgDeb: "python3-shodan",
			PkgAliasArch: []string{"python3-shodan"},
			Ecosystem: EcosystemPip, EcosystemPkg: "shodan",
			Cmd: "shodan", KaliSlug: "shodan"},
		{Name: "amass", DisplayName: "Amass", Category: "Information Gathering",
			PkgArch: "amass", PkgDeb: "amass",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/owasp-amass/amass/v4/...@latest",
			Cmd: "amass", KaliSlug: "amass"},
		{Name: "subfinder", DisplayName: "Subfinder", Category: "Information Gathering",
			PkgArch: "subfinder", PkgDeb: "subfinder",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/projectdiscovery/subfinder/v2/cmd/subfinder@latest",
			Cmd: "subfinder", KaliSlug: "subfinder"},
		{Name: "fierce", DisplayName: "Fierce", Category: "Information Gathering",
			PkgArch: "fierce", PkgDeb: "fierce",
			Ecosystem: EcosystemPip, EcosystemPkg: "fierce",
			Cmd: "fierce", KaliSlug: "fierce"},
		{Name: "dnsrecon", DisplayName: "DNSRecon", Category: "Information Gathering",
			PkgArch: "dnsrecon", PkgDeb: "dnsrecon",
			Ecosystem: EcosystemPip, EcosystemPkg: "dnsrecon",
			Cmd: "dnsrecon", KaliSlug: "dnsrecon"},
		{Name: "dnsenum", DisplayName: "DNSenum", Category: "Information Gathering",
			PkgArch: "dnsenum", PkgDeb: "dnsenum", Cmd: "dnsenum", KaliSlug: "dnsenum"},
		{Name: "dnsx", DisplayName: "dnsx", Category: "Information Gathering",
			PkgArch: "dnsx", PkgDeb: "dnsx",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/projectdiscovery/dnsx/cmd/dnsx@latest",
			Cmd: "dnsx", KaliSlug: "dnsx"},
		{Name: "enum4linux", DisplayName: "Enum4linux", Category: "Information Gathering",
			PkgArch: "enum4linux", PkgDeb: "enum4linux", Cmd: "enum4linux", KaliSlug: "enum4linux"},
		{Name: "enum4linux-ng", DisplayName: "Enum4linux-ng", Category: "Information Gathering",
			PkgArch: "enum4linux-ng", PkgDeb: "enum4linux-ng",
			Ecosystem: EcosystemPip, EcosystemPkg: "enum4linux-ng",
			Cmd: "enum4linux-ng", KaliSlug: "enum4linux-ng"},
		{Name: "netdiscover", DisplayName: "Netdiscover", Category: "Information Gathering",
			PkgArch: "netdiscover", PkgDeb: "netdiscover", Cmd: "netdiscover", KaliSlug: "netdiscover"},
		{Name: "arp-scan", DisplayName: "ARP-Scan", Category: "Information Gathering",
			PkgArch: "arp-scan", PkgDeb: "arp-scan", Cmd: "arp-scan", KaliSlug: "arp-scan"},
		{Name: "dmitry", DisplayName: "DMitry", Category: "Information Gathering",
			PkgArch: "dmitry", PkgDeb: "dmitry", Cmd: "dmitry", KaliSlug: "dmitry"},
		{Name: "osrframework", DisplayName: "OSRFramework", Category: "Information Gathering",
			PkgArch: "osrframework", PkgDeb: "osrframework",
			Ecosystem: EcosystemPip, EcosystemPkg: "osrframework",
			Cmd: "usufy", KaliSlug: "osrframework"},
		{Name: "sn0int", DisplayName: "sn0int", Category: "Information Gathering",
			PkgArch: "sn0int", PkgDeb: "sn0int",
			Ecosystem: EcosystemCargo, EcosystemPkg: "sn0int",
			Cmd: "sn0int", KaliSlug: "sn0int"},
		{Name: "p0f", DisplayName: "p0f", Category: "Information Gathering",
			PkgArch: "p0f", PkgDeb: "p0f", Cmd: "p0f", KaliSlug: "p0f"},
		{Name: "smbmap", DisplayName: "SMBMap", Category: "Information Gathering",
			PkgArch: "smbmap", PkgDeb: "smbmap",
			Ecosystem: EcosystemPip, EcosystemPkg: "smbmap",
			Cmd: "smbmap", KaliSlug: "smbmap"},
		{Name: "nbtscan", DisplayName: "NBTscan", Category: "Information Gathering",
			PkgArch: "nbtscan", PkgDeb: "nbtscan", Cmd: "nbtscan", KaliSlug: "nbtscan"},
		{Name: "onesixtyone", DisplayName: "Onesixtyone", Category: "Information Gathering",
			PkgArch: "onesixtyone", PkgDeb: "onesixtyone", Cmd: "onesixtyone", KaliSlug: "onesixtyone"},
		{Name: "snmpcheck", DisplayName: "SNMPCheck", Category: "Information Gathering",
			PkgArch: "snmpcheck", PkgDeb: "snmpcheck", Cmd: "snmpcheck", KaliSlug: "snmpcheck"},
		{Name: "wafw00f", DisplayName: "WafW00f", Category: "Information Gathering",
			PkgArch: "wafw00f", PkgDeb: "wafw00f",
			Ecosystem: EcosystemPip, EcosystemPkg: "wafw00f",
			Cmd: "wafw00f", KaliSlug: "wafw00f"},
		{Name: "httpx", DisplayName: "httpx", Category: "Information Gathering",
			PkgArch: "httpx-toolkit", PkgDeb: "httpx-toolkit",
			PkgAliasArch: []string{"httpx-bin", "httpx"},
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/projectdiscovery/httpx/cmd/httpx@latest",
			Cmd: "httpx", KaliSlug: "httpx"},
		{Name: "hakrawler", DisplayName: "Hakrawler", Category: "Information Gathering",
			PkgArch: "hakrawler", PkgDeb: "hakrawler",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/hakluke/hakrawler@latest",
			Cmd: "hakrawler", KaliSlug: "hakrawler"},
		{Name: "katana", DisplayName: "Katana", Category: "Information Gathering",
			PkgArch: "katana", PkgDeb: "katana",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/projectdiscovery/katana/cmd/katana@latest",
			Cmd: "katana", KaliSlug: "katana"},
		{Name: "gau", DisplayName: "GAU", Category: "Information Gathering",
			PkgArch: "gau", PkgDeb: "gau",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/lc/gau/v2/cmd/gau@latest",
			Cmd: "gau", KaliSlug: "gau"},
		{Name: "gospider", DisplayName: "GoSpider", Category: "Information Gathering",
			PkgArch: "gospider", PkgDeb: "gospider",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/jaeles-project/gospider@latest",
			Cmd: "gospider", KaliSlug: "gospider"},
		{Name: "linkfinder", DisplayName: "LinkFinder", Category: "Information Gathering",
			PkgArch: "linkfinder", PkgDeb: "linkfinder",
			Ecosystem: EcosystemPip, EcosystemPkg: "LinkFinder",
			Cmd: "linkfinder", KaliSlug: "linkfinder"},

		// ── Vulnerability Analysis ───────────────────────────────────────────────
		{Name: "nikto", DisplayName: "Nikto", Category: "Vulnerability Analysis",
			PkgArch: "nikto", PkgDeb: "nikto", Cmd: "nikto", KaliSlug: "nikto"},
		{Name: "sqlmap", DisplayName: "SQLMap", Category: "Vulnerability Analysis",
			PkgArch: "sqlmap", PkgDeb: "sqlmap",
			Ecosystem: EcosystemPip, EcosystemPkg: "sqlmap",
			Cmd: "sqlmap", KaliSlug: "sqlmap"},
		{Name: "openvas", DisplayName: "OpenVAS / GVM", Category: "Vulnerability Analysis",
			PkgArch: "gvm", PkgDeb: "openvas",
			PkgAliasDeb: []string{"gvm", "greenbone-vulnerability-manager"},
			Cmd: "gvm-start", KaliSlug: "openvas"},
		{Name: "lynis", DisplayName: "Lynis", Category: "Vulnerability Analysis",
			PkgArch: "lynis", PkgDeb: "lynis", Cmd: "lynis", KaliSlug: "lynis"},
		{Name: "wpscan", DisplayName: "WPScan", Category: "Vulnerability Analysis",
			PkgArch: "wpscan", PkgDeb: "wpscan",
			Ecosystem: EcosystemGem, EcosystemPkg: "wpscan",
			Cmd: "wpscan", KaliSlug: "wpscan"},
		{Name: "joomscan", DisplayName: "JoomScan", Category: "Vulnerability Analysis",
			PkgArch: "joomscan", PkgDeb: "joomscan",
			Ecosystem: EcosystemPip, EcosystemPkg: "joomscan",
			Cmd: "joomscan", KaliSlug: "joomscan"},
		{Name: "droopescan", DisplayName: "Droopescan", Category: "Vulnerability Analysis",
			PkgArch: "droopescan", PkgDeb: "droopescan",
			Ecosystem: EcosystemPip, EcosystemPkg: "droopescan",
			Cmd: "droopescan", KaliSlug: "droopescan"},
		{Name: "nuclei", DisplayName: "Nuclei", Category: "Vulnerability Analysis",
			PkgArch: "nuclei", PkgDeb: "nuclei",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/projectdiscovery/nuclei/v3/cmd/nuclei@latest",
			Cmd: "nuclei", KaliSlug: "nuclei"},
		{Name: "legion", DisplayName: "Legion", Category: "Vulnerability Analysis",
			PkgArch: "legion", PkgDeb: "legion", Cmd: "legion", KaliSlug: "legion"},
		{Name: "unix-privesc-check", DisplayName: "Unix Privesc Check", Category: "Vulnerability Analysis",
			PkgArch: "unix-privesc-check", PkgDeb: "unix-privesc-check",
			Cmd: "unix-privesc-check", KaliSlug: "unix-privesc-check"},
		{Name: "linux-exploit-suggester", DisplayName: "Linux Exploit Suggester", Category: "Vulnerability Analysis",
			PkgArch: "linux-exploit-suggester", PkgDeb: "linux-exploit-suggester",
			Cmd: "linux-exploit-suggester", KaliSlug: "linux-exploit-suggester"},
		{Name: "retire-js", DisplayName: "Retire.js", Category: "Vulnerability Analysis",
			PkgArch: "retirejs", PkgDeb: "retirejs",
			Ecosystem: EcosystemNpm, EcosystemPkg: "retire",
			Cmd: "retire", KaliSlug: "retire-js"},
		{Name: "vulners", DisplayName: "Vulners Scanner", Category: "Vulnerability Analysis",
			PkgArch: "python-vulners", PkgDeb: "python3-vulners",
			Ecosystem: EcosystemPip, EcosystemPkg: "vulners",
			Cmd: "vulners", KaliSlug: "vulners"},

		// ── Web Application ──────────────────────────────────────────────────────
		{Name: "burpsuite", DisplayName: "Burp Suite", Category: "Web Application",
			PkgArch: "burpsuite", PkgDeb: "burpsuite", Cmd: "burpsuite", KaliSlug: "burpsuite"},
		{Name: "zaproxy", DisplayName: "OWASP ZAP", Category: "Web Application",
			PkgArch: "zaproxy", PkgDeb: "zaproxy",
			PkgAliasDeb: []string{"owasp-zap"},
			Cmd: "zaproxy", KaliSlug: "zaproxy"},
		{Name: "gobuster", DisplayName: "Gobuster", Category: "Web Application",
			PkgArch: "gobuster", PkgDeb: "gobuster",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/OJ/gobuster/v3@latest",
			Cmd: "gobuster", KaliSlug: "gobuster"},
		{Name: "feroxbuster", DisplayName: "Feroxbuster", Category: "Web Application",
			PkgArch: "feroxbuster", PkgDeb: "feroxbuster",
			Ecosystem: EcosystemCargo, EcosystemPkg: "feroxbuster",
			Cmd: "feroxbuster", KaliSlug: "feroxbuster"},
		{Name: "ffuf", DisplayName: "ffuf", Category: "Web Application",
			PkgArch: "ffuf", PkgDeb: "ffuf",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/ffuf/ffuf/v2@latest",
			Cmd: "ffuf", KaliSlug: "ffuf"},
		{Name: "dirb", DisplayName: "DIRB", Category: "Web Application",
			PkgArch: "dirb", PkgDeb: "dirb", Cmd: "dirb", KaliSlug: "dirb"},
		{Name: "dirbuster", DisplayName: "DirBuster", Category: "Web Application",
			PkgArch: "dirbuster", PkgDeb: "dirbuster", Cmd: "dirbuster", KaliSlug: "dirbuster"},
		{Name: "wfuzz", DisplayName: "Wfuzz", Category: "Web Application",
			PkgArch: "wfuzz", PkgDeb: "wfuzz",
			Ecosystem: EcosystemPip, EcosystemPkg: "wfuzz",
			Cmd: "wfuzz", KaliSlug: "wfuzz"},
		{Name: "commix", DisplayName: "Commix", Category: "Web Application",
			PkgArch: "commix", PkgDeb: "commix",
			Ecosystem: EcosystemPip, EcosystemPkg: "commix",
			Cmd: "commix", KaliSlug: "commix"},
		{Name: "xsser", DisplayName: "XSSer", Category: "Web Application",
			PkgArch: "xsser", PkgDeb: "xsser",
			Ecosystem: EcosystemPip, EcosystemPkg: "XSSer",
			Cmd: "xsser", KaliSlug: "xsser"},
		{Name: "davtest", DisplayName: "DAVTest", Category: "Web Application",
			PkgArch: "davtest", PkgDeb: "davtest", Cmd: "davtest", KaliSlug: "davtest"},
		{Name: "cadaver", DisplayName: "Cadaver", Category: "Web Application",
			PkgArch: "cadaver", PkgDeb: "cadaver", Cmd: "cadaver", KaliSlug: "cadaver"},
		{Name: "sqlninja", DisplayName: "SQLNinja", Category: "Web Application",
			PkgArch: "sqlninja", PkgDeb: "sqlninja", Cmd: "sqlninja", KaliSlug: "sqlninja"},
		{Name: "wapiti", DisplayName: "Wapiti", Category: "Web Application",
			PkgArch: "wapiti", PkgDeb: "wapiti",
			Ecosystem: EcosystemPip, EcosystemPkg: "wapiti3",
			Cmd: "wapiti", KaliSlug: "wapiti"},
		{Name: "httrack", DisplayName: "HTTrack", Category: "Web Application",
			PkgArch: "httrack", PkgDeb: "httrack", Cmd: "httrack", KaliSlug: "httrack"},
		{Name: "arjun", DisplayName: "Arjun", Category: "Web Application",
			PkgArch: "arjun", PkgDeb: "arjun",
			Ecosystem: EcosystemPip, EcosystemPkg: "arjun",
			Cmd: "arjun", KaliSlug: "arjun"},
		{Name: "dalfox", DisplayName: "Dalfox", Category: "Web Application",
			PkgArch: "dalfox", PkgDeb: "dalfox",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/hahwul/dalfox/v2@latest",
			Cmd: "dalfox", KaliSlug: "dalfox"},
		{Name: "ghauri", DisplayName: "Ghauri", Category: "Web Application",
			PkgArch: "ghauri", PkgDeb: "ghauri",
			Ecosystem: EcosystemPip, EcosystemPkg: "ghauri",
			Cmd: "ghauri", KaliSlug: "ghauri"},
		{Name: "bypass-403", DisplayName: "Bypass 403", Category: "Web Application",
			PkgArch: "bypass-403", PkgDeb: "bypass-403",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/iamj0ker/bypass-403@latest",
			Cmd: "bypass-403", KaliSlug: "bypass-403"},

		// ── Exploitation ─────────────────────────────────────────────────────────
		{Name: "metasploit", DisplayName: "Metasploit Framework", Category: "Exploitation",
			PkgArch: "metasploit", PkgDeb: "metasploit-framework",
			PkgAliasDeb: []string{"metasploit"},
			Cmd: "msfconsole", KaliSlug: "metasploit-framework"},
		{Name: "msfvenom", DisplayName: "Msfvenom", Category: "Exploitation",
			PkgArch: "metasploit", PkgDeb: "metasploit-framework",
			Cmd: "msfvenom", KaliSlug: "msfvenom"},
		{Name: "exploitdb", DisplayName: "ExploitDB / Searchsploit", Category: "Exploitation",
			PkgArch: "exploitdb", PkgDeb: "exploitdb",
			Cmd: "searchsploit", KaliSlug: "exploitdb"},
		{Name: "beef-xss", DisplayName: "BeEF XSS", Category: "Exploitation",
			PkgArch: "beef-xss", PkgDeb: "beef-xss",
			Ecosystem: EcosystemGem, EcosystemPkg: "beef-xss",
			Cmd: "beef-xss", KaliSlug: "beef-xss"},
		{Name: "set", DisplayName: "Social Engineering Toolkit", Category: "Exploitation",
			PkgArch: "set", PkgDeb: "set",
			PkgAliasDeb: []string{"social-engineer-toolkit"},
			Ecosystem: EcosystemPip, EcosystemPkg: "setoolkit",
			Cmd: "setoolkit", KaliSlug: "set"},
		{Name: "veil", DisplayName: "Veil Framework", Category: "Exploitation",
			PkgArch: "veil", PkgDeb: "veil", Cmd: "veil", KaliSlug: "veil"},
		{Name: "shellter", DisplayName: "Shellter", Category: "Exploitation",
			PkgArch: "shellter", PkgDeb: "shellter", Cmd: "shellter", KaliSlug: "shellter"},
		{Name: "routersploit", DisplayName: "RouterSploit", Category: "Exploitation",
			PkgArch: "routersploit", PkgDeb: "routersploit",
			Ecosystem: EcosystemPip, EcosystemPkg: "routersploit",
			Cmd: "rsf", KaliSlug: "routersploit"},
		{Name: "armitage", DisplayName: "Armitage", Category: "Exploitation",
			PkgArch: "armitage", PkgDeb: "armitage", Cmd: "armitage", KaliSlug: "armitage"},
		{Name: "yersinia", DisplayName: "Yersinia", Category: "Exploitation",
			PkgArch: "yersinia", PkgDeb: "yersinia", Cmd: "yersinia", KaliSlug: "yersinia"},
		{Name: "donut-injector", DisplayName: "Donut Injector", Category: "Exploitation",
			PkgArch: "donut", PkgDeb: "donut-injector",
			Ecosystem: EcosystemPip, EcosystemPkg: "donut-shellcode",
			Cmd: "donut", KaliSlug: "donut-injector"},

		// ── Password Attacks ─────────────────────────────────────────────────────
		{Name: "john", DisplayName: "John the Ripper", Category: "Password Attacks",
			PkgArch: "john", PkgDeb: "john",
			PkgAliasDeb: []string{"john-data"},
			Cmd: "john", KaliSlug: "john"},
		{Name: "hashcat", DisplayName: "Hashcat", Category: "Password Attacks",
			PkgArch: "hashcat", PkgDeb: "hashcat", Cmd: "hashcat", KaliSlug: "hashcat"},
		{Name: "hydra", DisplayName: "THC Hydra", Category: "Password Attacks",
			PkgArch: "thc-hydra", PkgDeb: "hydra",
			PkgAliasArch: []string{"hydra"},
			PkgAliasDeb:  []string{"thc-hydra"},
			Cmd: "hydra", KaliSlug: "hydra"},
		{Name: "medusa", DisplayName: "Medusa", Category: "Password Attacks",
			PkgArch: "medusa", PkgDeb: "medusa", Cmd: "medusa", KaliSlug: "medusa"},
		{Name: "ncrack", DisplayName: "Ncrack", Category: "Password Attacks",
			PkgArch: "ncrack", PkgDeb: "ncrack", Cmd: "ncrack", KaliSlug: "ncrack"},
		{Name: "patator", DisplayName: "Patator", Category: "Password Attacks",
			PkgArch: "patator", PkgDeb: "patator",
			Ecosystem: EcosystemPip, EcosystemPkg: "patator",
			Cmd: "patator", KaliSlug: "patator"},
		{Name: "crunch", DisplayName: "Crunch", Category: "Password Attacks",
			PkgArch: "crunch", PkgDeb: "crunch", Cmd: "crunch", KaliSlug: "crunch"},
		{Name: "cewl", DisplayName: "CeWL", Category: "Password Attacks",
			PkgArch: "cewl", PkgDeb: "cewl",
			Ecosystem: EcosystemGem, EcosystemPkg: "cewl",
			Cmd: "cewl", KaliSlug: "cewl"},
		{Name: "wordlistctl", DisplayName: "Wordlistctl", Category: "Password Attacks",
			PkgArch: "wordlistctl", PkgDeb: "wordlistctl",
			Ecosystem: EcosystemPip, EcosystemPkg: "wordlistctl",
			Cmd: "wordlistctl", KaliSlug: "wordlistctl"},
		{Name: "rsmangler", DisplayName: "RSMangler", Category: "Password Attacks",
			PkgArch: "rsmangler", PkgDeb: "rsmangler", Cmd: "rsmangler", KaliSlug: "rsmangler"},
		{Name: "hashid", DisplayName: "HashID", Category: "Password Attacks",
			PkgArch: "hashid", PkgDeb: "hashid",
			Ecosystem: EcosystemPip, EcosystemPkg: "hashid",
			Cmd: "hashid", KaliSlug: "hashid"},
		{Name: "hash-identifier", DisplayName: "Hash Identifier", Category: "Password Attacks",
			PkgArch: "hash-identifier", PkgDeb: "hash-identifier",
			Cmd: "hash-identifier", KaliSlug: "hash-identifier"},
		{Name: "ophcrack", DisplayName: "Ophcrack", Category: "Password Attacks",
			PkgArch: "ophcrack", PkgDeb: "ophcrack", Cmd: "ophcrack", KaliSlug: "ophcrack"},
		{Name: "fcrackzip", DisplayName: "FCrackZip", Category: "Password Attacks",
			PkgArch: "fcrackzip", PkgDeb: "fcrackzip", Cmd: "fcrackzip", KaliSlug: "fcrackzip"},
		{Name: "pdfcrack", DisplayName: "PDFCrack", Category: "Password Attacks",
			PkgArch: "pdfcrack", PkgDeb: "pdfcrack", Cmd: "pdfcrack", KaliSlug: "pdfcrack"},
		{Name: "brutespray", DisplayName: "BruteSpray", Category: "Password Attacks",
			PkgArch: "brutespray", PkgDeb: "brutespray",
			Ecosystem: EcosystemPip, EcosystemPkg: "brutespray",
			Cmd: "brutespray", KaliSlug: "brutespray"},
		{Name: "rainbowcrack", DisplayName: "RainbowCrack", Category: "Password Attacks",
			PkgArch: "rainbowcrack", PkgDeb: "rainbowcrack", Cmd: "rcrack", KaliSlug: "rainbowcrack"},

		// ── Wireless Attacks ─────────────────────────────────────────────────────
		{Name: "aircrack-ng", DisplayName: "Aircrack-ng", Category: "Wireless Attacks",
			PkgArch: "aircrack-ng", PkgDeb: "aircrack-ng", Cmd: "aircrack-ng", KaliSlug: "aircrack-ng"},
		{Name: "airodump-ng", DisplayName: "Airodump-ng", Category: "Wireless Attacks",
			PkgArch: "aircrack-ng", PkgDeb: "aircrack-ng", Cmd: "airodump-ng", KaliSlug: "airodump-ng"},
		{Name: "kismet", DisplayName: "Kismet", Category: "Wireless Attacks",
			PkgArch: "kismet", PkgDeb: "kismet", Cmd: "kismet", KaliSlug: "kismet"},
		{Name: "reaver", DisplayName: "Reaver", Category: "Wireless Attacks",
			PkgArch: "reaver", PkgDeb: "reaver", Cmd: "reaver", KaliSlug: "reaver"},
		{Name: "wifite", DisplayName: "Wifite", Category: "Wireless Attacks",
			PkgArch: "wifite", PkgDeb: "wifite",
			Ecosystem: EcosystemPip, EcosystemPkg: "wifite",
			Cmd: "wifite", KaliSlug: "wifite"},
		{Name: "pixiewps", DisplayName: "PixieWPS", Category: "Wireless Attacks",
			PkgArch: "pixiewps", PkgDeb: "pixiewps", Cmd: "pixiewps", KaliSlug: "pixiewps"},
		{Name: "hostapd-wpe", DisplayName: "Hostapd-WPE", Category: "Wireless Attacks",
			PkgArch: "hostapd-wpe", PkgDeb: "hostapd-wpe", Cmd: "hostapd-wpe", KaliSlug: "hostapd-wpe"},
		{Name: "fern-wifi-cracker", DisplayName: "Fern Wifi Cracker", Category: "Wireless Attacks",
			PkgArch: "fern-wifi-cracker", PkgDeb: "fern-wifi-cracker", Cmd: "fern-wifi-cracker", KaliSlug: "fern-wifi-cracker"},
		{Name: "bully", DisplayName: "Bully", Category: "Wireless Attacks",
			PkgArch: "bully", PkgDeb: "bully", Cmd: "bully", KaliSlug: "bully"},
		{Name: "mdk4", DisplayName: "MDK4", Category: "Wireless Attacks",
			PkgArch: "mdk4", PkgDeb: "mdk4", Cmd: "mdk4", KaliSlug: "mdk4"},
		{Name: "eaphammer", DisplayName: "EAPHammer", Category: "Wireless Attacks",
			PkgArch: "eaphammer", PkgDeb: "eaphammer",
			Ecosystem: EcosystemPip, EcosystemPkg: "eaphammer",
			Cmd: "eaphammer", KaliSlug: "eaphammer"},
		{Name: "wifi-honey", DisplayName: "Wifi-Honey", Category: "Wireless Attacks",
			PkgArch: "wifi-honey", PkgDeb: "wifi-honey", Cmd: "wifi-honey", KaliSlug: "wifi-honey"},

		// ── Sniffing & Spoofing ──────────────────────────────────────────────────
		{Name: "wireshark", DisplayName: "Wireshark", Category: "Sniffing & Spoofing",
			PkgArch: "wireshark-qt", PkgDeb: "wireshark",
			PkgAliasArch: []string{"wireshark"},
			Cmd: "wireshark", KaliSlug: "wireshark"},
		{Name: "tshark", DisplayName: "TShark", Category: "Sniffing & Spoofing",
			PkgArch: "wireshark-cli", PkgDeb: "tshark",
			PkgAliasArch: []string{"wireshark"},
			Cmd: "tshark", KaliSlug: "tshark"},
		{Name: "tcpdump", DisplayName: "tcpdump", Category: "Sniffing & Spoofing",
			PkgArch: "tcpdump", PkgDeb: "tcpdump", Cmd: "tcpdump", KaliSlug: "tcpdump"},
		{Name: "ettercap", DisplayName: "Ettercap", Category: "Sniffing & Spoofing",
			PkgArch: "ettercap", PkgDeb: "ettercap-graphical",
			PkgAliasDeb: []string{"ettercap-text-only", "ettercap-common"},
			Cmd: "ettercap", KaliSlug: "ettercap"},
		{Name: "bettercap", DisplayName: "Bettercap", Category: "Sniffing & Spoofing",
			PkgArch: "bettercap", PkgDeb: "bettercap",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/bettercap/bettercap@latest",
			Cmd: "bettercap", KaliSlug: "bettercap"},
		{Name: "responder", DisplayName: "Responder", Category: "Sniffing & Spoofing",
			PkgArch: "responder", PkgDeb: "responder",
			Ecosystem: EcosystemPip, EcosystemPkg: "responder",
			Cmd: "responder", KaliSlug: "responder"},
		{Name: "mitm6", DisplayName: "mitm6", Category: "Sniffing & Spoofing",
			PkgArch: "mitm6", PkgDeb: "mitm6",
			Ecosystem: EcosystemPip, EcosystemPkg: "mitm6",
			Cmd: "mitm6", KaliSlug: "mitm6"},
		{Name: "arpwatch", DisplayName: "Arpwatch", Category: "Sniffing & Spoofing",
			PkgArch: "arpwatch", PkgDeb: "arpwatch", Cmd: "arpwatch", KaliSlug: "arpwatch"},
		{Name: "macchanger", DisplayName: "Macchanger", Category: "Sniffing & Spoofing",
			PkgArch: "macchanger", PkgDeb: "macchanger", Cmd: "macchanger", KaliSlug: "macchanger"},
		{Name: "netsniff-ng", DisplayName: "Netsniff-ng", Category: "Sniffing & Spoofing",
			PkgArch: "netsniff-ng", PkgDeb: "netsniff-ng", Cmd: "netsniff-ng", KaliSlug: "netsniff-ng"},
		{Name: "dnschef", DisplayName: "DNSChef", Category: "Sniffing & Spoofing",
			PkgArch: "dnschef", PkgDeb: "dnschef",
			Ecosystem: EcosystemPip, EcosystemPkg: "dnschef",
			Cmd: "dnschef", KaliSlug: "dnschef"},
		{Name: "mitmproxy", DisplayName: "mitmproxy", Category: "Sniffing & Spoofing",
			PkgArch: "mitmproxy", PkgDeb: "mitmproxy",
			Ecosystem: EcosystemPip, EcosystemPkg: "mitmproxy",
			Cmd: "mitmproxy", KaliSlug: "mitmproxy"},
		{Name: "sslstrip", DisplayName: "SSLstrip", Category: "Sniffing & Spoofing",
			PkgArch: "sslstrip", PkgDeb: "sslstrip",
			Ecosystem: EcosystemPip, EcosystemPkg: "sslstrip",
			Cmd: "sslstrip", KaliSlug: "sslstrip"},

		// ── Post Exploitation ────────────────────────────────────────────────────
		{Name: "empire", DisplayName: "PowerShell Empire", Category: "Post Exploitation",
			PkgArch: "powershell-empire", PkgDeb: "powershell-empire",
			Ecosystem: EcosystemPip, EcosystemPkg: "powershell-empire",
			Cmd: "powershell-empire", KaliSlug: "powershell-empire"},
		{Name: "mimikatz", DisplayName: "Mimikatz", Category: "Post Exploitation",
			PkgArch: "mimikatz", PkgDeb: "mimikatz", Cmd: "mimikatz", KaliSlug: "mimikatz"},
		{Name: "crackmapexec", DisplayName: "CrackMapExec", Category: "Post Exploitation",
			PkgArch: "crackmapexec", PkgDeb: "crackmapexec",
			Ecosystem: EcosystemPip, EcosystemPkg: "crackmapexec",
			Cmd: "cme", KaliSlug: "crackmapexec"},
		{Name: "netexec", DisplayName: "NetExec", Category: "Post Exploitation",
			PkgArch: "netexec", PkgDeb: "netexec",
			Ecosystem: EcosystemPip, EcosystemPkg: "netexec",
			Cmd: "nxc", KaliSlug: "netexec"},
		{Name: "impacket", DisplayName: "Impacket", Category: "Post Exploitation",
			PkgArch: "impacket", PkgDeb: "python3-impacket",
			PkgAliasArch: []string{"python-impacket"},
			PkgAliasDeb:  []string{"impacket-scripts"},
			Ecosystem: EcosystemPip, EcosystemPkg: "impacket",
			Cmd: "impacket-secretsdump", KaliSlug: "impacket"},
		{Name: "bloodhound", DisplayName: "BloodHound", Category: "Post Exploitation",
			PkgArch: "bloodhound", PkgDeb: "bloodhound",
			Ecosystem: EcosystemNpm, EcosystemPkg: "bloodhound",
			Cmd: "bloodhound", KaliSlug: "bloodhound"},
		{Name: "evil-winrm", DisplayName: "Evil-WinRM", Category: "Post Exploitation",
			PkgArch: "evil-winrm", PkgDeb: "evil-winrm",
			Ecosystem: EcosystemGem, EcosystemPkg: "evil-winrm",
			Cmd: "evil-winrm", KaliSlug: "evil-winrm"},
		{Name: "pwncat", DisplayName: "pwncat", Category: "Post Exploitation",
			PkgArch: "pwncat", PkgDeb: "pwncat",
			Ecosystem: EcosystemPip, EcosystemPkg: "pwncat-cs",
			Cmd: "pwncat", KaliSlug: "pwncat"},
		{Name: "starkiller", DisplayName: "Starkiller", Category: "Post Exploitation",
			PkgArch: "starkiller", PkgDeb: "starkiller", Cmd: "starkiller", KaliSlug: "starkiller"},
		{Name: "sliver", DisplayName: "Sliver C2", Category: "Post Exploitation",
			PkgArch: "sliver", PkgDeb: "sliver",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/bishopfox/sliver/client@latest",
			Cmd: "sliver", KaliSlug: "sliver"},
		{Name: "havoc", DisplayName: "Havoc C2", Category: "Post Exploitation",
			PkgArch: "havoc", PkgDeb: "havoc", Cmd: "havoc", KaliSlug: "havoc"},

		// ── Forensics ────────────────────────────────────────────────────────────
		{Name: "autopsy", DisplayName: "Autopsy", Category: "Forensics",
			PkgArch: "autopsy", PkgDeb: "autopsy", Cmd: "autopsy", KaliSlug: "autopsy"},
		{Name: "binwalk", DisplayName: "Binwalk", Category: "Forensics",
			PkgArch: "binwalk", PkgDeb: "binwalk",
			Ecosystem: EcosystemPip, EcosystemPkg: "binwalk",
			Cmd: "binwalk", KaliSlug: "binwalk"},
		{Name: "volatility3", DisplayName: "Volatility 3", Category: "Forensics",
			PkgArch: "volatility3", PkgDeb: "volatility3",
			Ecosystem: EcosystemPip, EcosystemPkg: "volatility3",
			Cmd: "vol", KaliSlug: "volatility3"},
		{Name: "foremost", DisplayName: "Foremost", Category: "Forensics",
			PkgArch: "foremost", PkgDeb: "foremost", Cmd: "foremost", KaliSlug: "foremost"},
		{Name: "exiftool", DisplayName: "ExifTool", Category: "Forensics",
			PkgArch: "perl-image-exiftool", PkgDeb: "libimage-exiftool-perl",
			PkgAliasArch: []string{"exiftool"},
			PkgAliasDeb:  []string{"exiftool"},
			Cmd: "exiftool", KaliSlug: "exiftool"},
		{Name: "bulk-extractor", DisplayName: "Bulk Extractor", Category: "Forensics",
			PkgArch: "bulk-extractor", PkgDeb: "bulk-extractor", Cmd: "bulk_extractor", KaliSlug: "bulk-extractor"},
		{Name: "dc3dd", DisplayName: "dc3dd", Category: "Forensics",
			PkgArch: "dc3dd", PkgDeb: "dc3dd", Cmd: "dc3dd", KaliSlug: "dc3dd"},
		{Name: "dcfldd", DisplayName: "dcfldd", Category: "Forensics",
			PkgArch: "dcfldd", PkgDeb: "dcfldd", Cmd: "dcfldd", KaliSlug: "dcfldd"},
		{Name: "testdisk", DisplayName: "TestDisk", Category: "Forensics",
			PkgArch: "testdisk", PkgDeb: "testdisk", Cmd: "testdisk", KaliSlug: "testdisk"},
		{Name: "scalpel", DisplayName: "Scalpel", Category: "Forensics",
			PkgArch: "scalpel", PkgDeb: "scalpel", Cmd: "scalpel", KaliSlug: "scalpel"},
		{Name: "extundelete", DisplayName: "extundelete", Category: "Forensics",
			PkgArch: "extundelete", PkgDeb: "extundelete", Cmd: "extundelete", KaliSlug: "extundelete"},
		{Name: "pdf-parser", DisplayName: "PDF Parser", Category: "Forensics",
			PkgArch: "pdf-parser", PkgDeb: "pdf-parser",
			Ecosystem: EcosystemPip, EcosystemPkg: "pdf-parser",
			Cmd: "pdf-parser", KaliSlug: "pdf-parser"},
		{Name: "pdfid", DisplayName: "PDFiD", Category: "Forensics",
			PkgArch: "pdfid", PkgDeb: "pdfid",
			Ecosystem: EcosystemPip, EcosystemPkg: "pdfid",
			Cmd: "pdfid", KaliSlug: "pdfid"},
		{Name: "networkminer", DisplayName: "NetworkMiner", Category: "Forensics",
			PkgArch: "networkminer", PkgDeb: "networkminer", Cmd: "networkminer", KaliSlug: "networkminer"},
		{Name: "hexedit", DisplayName: "Hexedit", Category: "Forensics",
			PkgArch: "hexedit", PkgDeb: "hexedit", Cmd: "hexedit", KaliSlug: "hexedit"},
		{Name: "ghex", DisplayName: "GHex", Category: "Forensics",
			PkgArch: "ghex", PkgDeb: "ghex", Cmd: "ghex", KaliSlug: "ghex"},

		// ── Reverse Engineering ──────────────────────────────────────────────────
		{Name: "ghidra", DisplayName: "Ghidra", Category: "Reverse Engineering",
			PkgArch: "ghidra", PkgDeb: "ghidra", Cmd: "ghidra", KaliSlug: "ghidra"},
		{Name: "radare2", DisplayName: "Radare2", Category: "Reverse Engineering",
			PkgArch: "radare2", PkgDeb: "radare2",
			Ecosystem: EcosystemPip, EcosystemPkg: "r2pipe",
			Cmd: "r2", KaliSlug: "radare2"},
		{Name: "cutter", DisplayName: "Cutter", Category: "Reverse Engineering",
			PkgArch: "cutter", PkgDeb: "cutter", Cmd: "cutter", KaliSlug: "cutter"},
		{Name: "gdb-peda", DisplayName: "GDB + PEDA", Category: "Reverse Engineering",
			PkgArch: "gdb", PkgDeb: "gdb", Cmd: "gdb", KaliSlug: "gdb-peda"},
		{Name: "pwndbg", DisplayName: "pwndbg", Category: "Reverse Engineering",
			PkgArch: "pwndbg", PkgDeb: "pwndbg",
			Ecosystem: EcosystemPip, EcosystemPkg: "pwndbg",
			Cmd: "gdb", KaliSlug: "pwndbg"},
		{Name: "apktool", DisplayName: "APKTool", Category: "Reverse Engineering",
			PkgArch: "apktool", PkgDeb: "apktool", Cmd: "apktool", KaliSlug: "apktool"},
		{Name: "jadx", DisplayName: "JADX", Category: "Reverse Engineering",
			PkgArch: "jadx", PkgDeb: "jadx", Cmd: "jadx", KaliSlug: "jadx"},
		{Name: "bytecode-viewer", DisplayName: "Bytecode Viewer", Category: "Reverse Engineering",
			PkgArch: "bytecode-viewer", PkgDeb: "bytecode-viewer", Cmd: "bytecode-viewer", KaliSlug: "bytecode-viewer"},
		{Name: "edb-debugger", DisplayName: "EDB Debugger", Category: "Reverse Engineering",
			PkgArch: "edb", PkgDeb: "edb-debugger",
			PkgAliasArch: []string{"edb-debugger"},
			Cmd: "edb", KaliSlug: "edb-debugger"},
		{Name: "strace", DisplayName: "strace", Category: "Reverse Engineering",
			PkgArch: "strace", PkgDeb: "strace", Cmd: "strace", KaliSlug: "strace"},
		{Name: "ltrace", DisplayName: "ltrace", Category: "Reverse Engineering",
			PkgArch: "ltrace", PkgDeb: "ltrace", Cmd: "ltrace", KaliSlug: "ltrace"},
		{Name: "objdump", DisplayName: "objdump", Category: "Reverse Engineering",
			PkgArch: "binutils", PkgDeb: "binutils", Cmd: "objdump", KaliSlug: "binutils"},
		{Name: "yara", DisplayName: "YARA", Category: "Reverse Engineering",
			PkgArch: "yara", PkgDeb: "yara",
			Ecosystem: EcosystemPip, EcosystemPkg: "yara-python",
			Cmd: "yara", KaliSlug: "yara"},

		// ── Social Engineering ───────────────────────────────────────────────────
		{Name: "gophish", DisplayName: "GoPhish", Category: "Social Engineering",
			PkgArch: "gophish", PkgDeb: "gophish",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/gophish/gophish@latest",
			Cmd: "gophish", KaliSlug: "gophish"},
		{Name: "evilginx2", DisplayName: "Evilginx2", Category: "Social Engineering",
			PkgArch: "evilginx2", PkgDeb: "evilginx2",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/kgretzky/evilginx2@latest",
			Cmd: "evilginx2", KaliSlug: "evilginx2"},
		{Name: "king-phisher", DisplayName: "King Phisher", Category: "Social Engineering",
			PkgArch: "king-phisher", PkgDeb: "king-phisher",
			Ecosystem: EcosystemPip, EcosystemPkg: "king-phisher",
			Cmd: "king-phisher", KaliSlug: "king-phisher"},
		{Name: "msfpc", DisplayName: "MSFpc", Category: "Social Engineering",
			PkgArch: "msfpc", PkgDeb: "msfpc", Cmd: "msfpc", KaliSlug: "msfpc"},

		// ── Hardware Hacking ─────────────────────────────────────────────────────
		{Name: "arduino", DisplayName: "Arduino IDE", Category: "Hardware Hacking",
			PkgArch: "arduino", PkgDeb: "arduino",
			PkgAliasDeb: []string{"arduino-core"},
			Cmd: "arduino", KaliSlug: "arduino"},
		{Name: "flashrom", DisplayName: "Flashrom", Category: "Hardware Hacking",
			PkgArch: "flashrom", PkgDeb: "flashrom", Cmd: "flashrom", KaliSlug: "flashrom"},
		{Name: "openocd", DisplayName: "OpenOCD", Category: "Hardware Hacking",
			PkgArch: "openocd", PkgDeb: "openocd", Cmd: "openocd", KaliSlug: "openocd"},
		{Name: "minicom", DisplayName: "Minicom", Category: "Hardware Hacking",
			PkgArch: "minicom", PkgDeb: "minicom", Cmd: "minicom", KaliSlug: "minicom"},
		{Name: "hackrf", DisplayName: "HackRF Tools", Category: "Hardware Hacking",
			PkgArch: "hackrf", PkgDeb: "hackrf", Cmd: "hackrf_info", KaliSlug: "hackrf"},
		{Name: "rtl-sdr", DisplayName: "RTL-SDR", Category: "Hardware Hacking",
			PkgArch: "rtl-sdr", PkgDeb: "rtl-sdr", Cmd: "rtl_test", KaliSlug: "rtl-sdr"},
		{Name: "gqrx", DisplayName: "GQRX SDR", Category: "Hardware Hacking",
			PkgArch: "gqrx-sdr", PkgDeb: "gqrx-sdr",
			PkgAliasArch: []string{"gqrx"},
			Cmd: "gqrx", KaliSlug: "gqrx"},
		{Name: "gnuradio", DisplayName: "GNU Radio", Category: "Hardware Hacking",
			PkgArch: "gnuradio", PkgDeb: "gnuradio",
			PkgAliasDeb: []string{"gnuradio-dev"},
			Cmd: "gnuradio-companion", KaliSlug: "gnuradio"},

		// ── Crypto & Stego ───────────────────────────────────────────────────────
		{Name: "steghide", DisplayName: "Steghide", Category: "Crypto & Stego",
			PkgArch: "steghide", PkgDeb: "steghide", Cmd: "steghide", KaliSlug: "steghide"},
		{Name: "stegcracker", DisplayName: "StegCracker", Category: "Crypto & Stego",
			PkgArch: "stegcracker", PkgDeb: "stegcracker",
			Ecosystem: EcosystemPip, EcosystemPkg: "stegcracker",
			Cmd: "stegcracker", KaliSlug: "stegcracker"},
		{Name: "outguess", DisplayName: "Outguess", Category: "Crypto & Stego",
			PkgArch: "outguess", PkgDeb: "outguess", Cmd: "outguess", KaliSlug: "outguess"},
		{Name: "stegosuite", DisplayName: "Stegosuite", Category: "Crypto & Stego",
			PkgArch: "stegosuite", PkgDeb: "stegosuite", Cmd: "stegosuite", KaliSlug: "stegosuite"},
		{Name: "cryptcat", DisplayName: "Cryptcat", Category: "Crypto & Stego",
			PkgArch: "cryptcat", PkgDeb: "cryptcat", Cmd: "cryptcat", KaliSlug: "cryptcat"},
		{Name: "ssldump", DisplayName: "SSLdump", Category: "Crypto & Stego",
			PkgArch: "ssldump", PkgDeb: "ssldump", Cmd: "ssldump", KaliSlug: "ssldump"},
		{Name: "sslscan", DisplayName: "SSLscan", Category: "Crypto & Stego",
			PkgArch: "sslscan", PkgDeb: "sslscan", Cmd: "sslscan", KaliSlug: "sslscan"},
		{Name: "testssl", DisplayName: "testssl.sh", Category: "Crypto & Stego",
			PkgArch: "testssl.sh", PkgDeb: "testssl.sh",
			PkgAliasArch: []string{"testssl"},
			PkgAliasDeb:  []string{"testssl"},
			Cmd: "testssl", KaliSlug: "testssl-sh"},
		{Name: "xortool", DisplayName: "XorTool", Category: "Crypto & Stego",
			PkgArch: "xortool", PkgDeb: "xortool",
			Ecosystem: EcosystemPip, EcosystemPkg: "xortool",
			Cmd: "xortool", KaliSlug: "xortool"},
		{Name: "snow", DisplayName: "SNOW", Category: "Crypto & Stego",
			PkgArch: "snow", PkgDeb: "snow", Cmd: "snow", KaliSlug: "snow"},

		// ── Network Tools ────────────────────────────────────────────────────────
		{Name: "netcat", DisplayName: "Netcat", Category: "Network Tools",
			PkgArch: "openbsd-netcat", PkgDeb: "netcat-openbsd",
			PkgAliasArch: []string{"gnu-netcat", "netcat"},
			PkgAliasDeb:  []string{"netcat-traditional", "netcat"},
			Cmd: "nc", KaliSlug: "netcat"},
		{Name: "socat", DisplayName: "Socat", Category: "Network Tools",
			PkgArch: "socat", PkgDeb: "socat", Cmd: "socat", KaliSlug: "socat"},
		{Name: "ncat", DisplayName: "Ncat", Category: "Network Tools",
			PkgArch: "ncat", PkgDeb: "ncat",
			PkgAliasDeb: []string{"nmap"},
			Cmd: "ncat", KaliSlug: "ncat"},
		{Name: "proxychains4", DisplayName: "ProxyChains-NG", Category: "Network Tools",
			PkgArch: "proxychains-ng", PkgDeb: "proxychains4",
			PkgAliasArch: []string{"proxychains4"},
			PkgAliasDeb:  []string{"proxychains"},
			Cmd: "proxychains4", KaliSlug: "proxychains4"},
		{Name: "hping3", DisplayName: "hping3", Category: "Network Tools",
			PkgArch: "hping", PkgDeb: "hping3",
			PkgAliasArch: []string{"hping3"},
			Cmd: "hping3", KaliSlug: "hping3"},
		{Name: "scapy", DisplayName: "Scapy", Category: "Network Tools",
			PkgArch: "python-scapy", PkgDeb: "python3-scapy",
			PkgAliasArch: []string{"scapy", "python3-scapy"},
			Ecosystem: EcosystemPip, EcosystemPkg: "scapy",
			Cmd: "scapy", KaliSlug: "scapy"},
		{Name: "nemesis", DisplayName: "Nemesis", Category: "Network Tools",
			PkgArch: "nemesis", PkgDeb: "nemesis", Cmd: "nemesis", KaliSlug: "nemesis"},
		{Name: "traceroute", DisplayName: "Traceroute", Category: "Network Tools",
			PkgArch: "traceroute", PkgDeb: "traceroute", Cmd: "traceroute", KaliSlug: "traceroute"},
		{Name: "whois", DisplayName: "Whois", Category: "Network Tools",
			PkgArch: "whois", PkgDeb: "whois", Cmd: "whois", KaliSlug: "whois"},
		{Name: "ipcalc", DisplayName: "ipcalc", Category: "Network Tools",
			PkgArch: "ipcalc", PkgDeb: "ipcalc", Cmd: "ipcalc", KaliSlug: "ipcalc"},
		{Name: "stunnel4", DisplayName: "stunnel", Category: "Network Tools",
			PkgArch: "stunnel", PkgDeb: "stunnel4",
			PkgAliasArch: []string{"stunnel4"},
			Cmd: "stunnel", KaliSlug: "stunnel4"},
		{Name: "chisel", DisplayName: "Chisel", Category: "Network Tools",
			PkgArch: "chisel", PkgDeb: "chisel",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/jpillora/chisel@latest",
			Cmd: "chisel", KaliSlug: "chisel"},
		{Name: "ligolo-ng", DisplayName: "Ligolo-ng", Category: "Network Tools",
			PkgArch: "ligolo-ng", PkgDeb: "ligolo-ng",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/nicocha30/ligolo-ng/cmd/proxy@latest",
			Cmd: "ligolo-ng", KaliSlug: "ligolo-ng"},
		{Name: "proxify", DisplayName: "Proxify", Category: "Network Tools",
			PkgArch: "proxify", PkgDeb: "proxify",
			Ecosystem: EcosystemGo, EcosystemPkg: "github.com/projectdiscovery/proxify/cmd/proxify@latest",
			Cmd: "proxify", KaliSlug: "proxify"},

		// ── Reporting ────────────────────────────────────────────────────────────
		{Name: "faraday", DisplayName: "Faraday IDE", Category: "Reporting",
			PkgArch: "faraday", PkgDeb: "faraday",
			Ecosystem: EcosystemPip, EcosystemPkg: "faradaysec",
			Cmd: "faraday-server", KaliSlug: "faraday"},
		{Name: "pipal", DisplayName: "Pipal", Category: "Reporting",
			PkgArch: "pipal", PkgDeb: "pipal",
			Ecosystem: EcosystemGem, EcosystemPkg: "pipal",
			Cmd: "pipal", KaliSlug: "pipal"},
		{Name: "dradis", DisplayName: "Dradis Framework", Category: "Reporting",
			PkgArch: "dradis", PkgDeb: "dradis",
			Ecosystem: EcosystemGem, EcosystemPkg: "dradis",
			Cmd: "dradis", KaliSlug: "dradis"},
		{Name: "metagoofil", DisplayName: "Metagoofil", Category: "Reporting",
			PkgArch: "metagoofil", PkgDeb: "metagoofil",
			Ecosystem: EcosystemPip, EcosystemPkg: "metagoofil",
			Cmd: "metagoofil", KaliSlug: "metagoofil"},
	}
}

// Categories returns a deduplicated list of category names in insertion order.
func Categories() []string {
	seen := map[string]struct{}{}
	var order []string
	for _, t := range AllTools() {
		if _, ok := seen[t.Category]; !ok {
			seen[t.Category] = struct{}{}
			order = append(order, t.Category)
		}
	}
	return order
}

// ByCategory groups tools into a map keyed by category.
func ByCategory() map[string][]Tool {
	out := map[string][]Tool{}
	for _, t := range AllTools() {
		out[t.Category] = append(out[t.Category], t)
	}
	return out
}
